name: Docker build

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: app-node

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build the Docker image
        run: docker build -t ${{env.IMAGE_NAME}}:1.0.0 .
      
      - name: Check image build
        run: docker image ls

